services:
  webapp:
    image: 075179376767.dkr.ecr.ap-southeast-1.amazonaws.com/medblock/web-webapp:latest
    container_name: medblock-webapp
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - medblock-network

networks:
  medblock-network:
    driver: bridge


