services:
  webapp:
    image: 075179376767.dkr.ecr.ap-southeast-1.amazonaws.com/medblock/web-webapp:staging-latest
    container_name: medblock-webapp
    ports:
      - "4001:3001"
    restart: unless-stopped
    networks:
      - medblock-staging-network

networks:
  medblock-staging-network:
    driver: bridge
