[package]
name = "canister_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-stable-structures = { workspace = true }
parity-scale-codec = { workspace = true }
