services:
  webapp:
    image: 075179376767.dkr.ecr.ap-southeast-1.amazonaws.com/medblock/web-pwa:staging-latest
    container_name: medblock-pwa
    env_file:
      - .env
    ports:
      - "4000:3000"
    restart: unless-stopped
    networks:
      - medblock-staging-network

networks:
  medblock-staging-network:
    driver: bridge

