version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.pwa
    container_name: medblock-pwa
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - medblock-network

networks:
  medblock-network:
    driver: bridge
