export default class Strings {
  static readonly label = {
    username: 'label.username',
    continueEmail: 'label.continueEmail',
    orContinue: 'label.orContinue',
    continuePassKey: 'label.continuePassKey',
    otherSign: 'label.otherSign',
    terms: 'label.terms',
    privacyPolicy: 'label.privacyPolicy',
    welcome: 'label.welcome',
    verifyYourId: 'label.verifyYourId',
    fullname: 'label.fullname',
    validIdNumber: 'label.validIdNumber',
    address: 'label.address',
    phoneNumber: 'label.phoneNumber',
    uploadYourIdCard: 'label.uploadYourIdCard',
    submit: 'label.submit',
    takePhoto: 'label.takePhoto',
    uploadFile: 'label.uploadFile',
    loading: 'label.loading',
    continue: 'label.continue',
    yourAccVerified: 'label.yourAccVerified',
    emrId: 'label.emrId',
    shareCode: 'label.shareCode',
    emptyEmr: 'label.emptyEmr',
    refreshCode: 'label.refreshCode',
    getNewCode: 'label.getNewCode',
    back: 'label.back',
    closeAccess: 'label.closeAccess',
    profileInfo: 'label.profileInfo',
    latestVisit: 'label.latestVisit',
    medicalOfficer: 'label.medicalOfficer',
    visitSummary: 'label.visitSummary',
    reasonVisit: 'label.reasonVisit',
    diagnosis: 'label.diagnosis',
    planning: 'label.planning',
    medication: 'label.medication',
    personalInfo: 'label.personalInfo',
    socialStatus: 'label.socialStatus',
    homeAddress: 'label.homeAddress',
    birthDate: 'label.birthDate',
    ethnicity: 'label.ethnicity',
    language: 'label.language',
    religion: 'label.religion',
    martialStatus: 'label.martialStatus',
    partner: 'label.partner',
    children: 'label.children',
    lastVisited: 'label.lastVisited',
    physician: 'label.physician',
    revokeEmr: 'label.revokeEmr',
    yes: 'label.yes',
    no: 'label.no',
    alert: 'label.alert',
    logout: 'label.logout',
    notification: 'label.notification',
    filter: 'label.filter',
    sort: 'label.sort',
  };

  static readonly message = {
    verifyYourId: 'message.verifyYourId',
    agreeTerm: 'message.agreeTerm',
    yourAccVerified: 'message.yourAccVerified',
    emptyEmr: 'message.emptyEmr',
    shareConsentCode: 'message.shareConsentCode',
    findAndRevoke: 'message.findAndRevoke',
    closeEmr: 'message.closeEmr',
    emrClosed: 'message.emrClosed',
    logout: 'message.logout',
  };

  static readonly validation = {
    fileMax2Mb: 'validation.fileMax2Mb',
  };

  static readonly navigation = {
    home: 'navigation.home',
    file: 'navigation.file',
    history: 'navigation.history',
    setting: 'navigation.setting',
  };

  static readonly placeholder = {
    search: 'placeholder.search',
  };
}
