name: Deploy PWA to Production

on:
  push:
    branches:
      - main
    paths:
      - final_demo/pwa/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_NAME: ${{ secrets.PWA_IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: [self-hosted, production]

    steps:
      - name: Check out code
        run: |
          cd /home/ubuntu/Medblock
          git pull
   
      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest -f /home/ubuntu/Medblock/final_demo/pwa/Dockerfile.pwa /home/ubuntu/Medblock/final_demo/pwa/

      - name: Push Docker Image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest

  deploy:
    runs-on: [self-hosted, production]
    needs: build-and-push

    steps:
      - name: Deploy to Server
        run: |
          cd /home/ubuntu/Medblock/final_demo/pwa
          docker compose down
          docker compose pull webapp
          docker compose up -d
