name: Deploy final_demo/pwa to Staging

on:
  push:
    branches:
      - staging
    paths:
      - final_demo/pwa/**

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_NAME: ${{ secrets.PWA_IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: [ arm64, medblock ]

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get commit hash
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG -f final_demo/pwa/Dockerfile.pwa final_demo/pwa/

      - name: Push Docker Image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: Checkout ArgoCD Repo
        run: git clone git@github.com:baliola/devops.git

      - name: Update image tag in deployment manifest
        run: |
          cd devops
          sed -i 's|image: 075179376767.dkr.ecr.ap-southeast-1.amazonaws.com/medblock/web-pwa:.*|image: 075179376767.dkr.ecr.ap-southeast-1.amazonaws.com/medblock/web-pwa:'"$IMAGE_TAG"'|' staging/medblock/pwa/deployment.yaml
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add staging/medblock/pwa/deployment.yaml
          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping commit and push."
            exit 0
          fi
          git commit -m "Update $IMAGE_NAME image to $IMAGE_TAG"
          git push origin main
